version = 3.9.9

runner.dialect = Scala213Source3
preset = IntelliJ

rewrite.rules = [
  RedundantParens,
  RedundantBraces,
  SortImports
]
#rewrite.scala3.convertToNewSyntax = false
#runner.dialectOverride.allowSignificantIndentation = false

danglingParentheses.preset = true
includeCurlyBraceInSelectChains = false
align.preset = some
